In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))        

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-diseaseuci/heart.csv


In [2]:
df = pd.read_csv('/kaggle/input/heart-diseaseuci/heart.csv')
print(df.shape)
df.sample(10)

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
261   52    1   0       112   230    0        1      160      0      0.0   
94    45    0   1       112   160    0        1      138      0      0.0   
66    51    1   2       100   222    0        1      143      1      1.2   
29    53    1   2       130   197    1        0      152      0      1.2   
296   63    0   0       124   197    0        1      136      1      0.0   
230   47    1   2       108   243    0        1      152      0      0.0   
25    71    0   1       160   302    0        1      162      0      0.4   
111   57    1   2       150   126    1        1      173      0      0.2   
84    42    0   0       102   265    0        0      122      0      0.6   
258   62    0   0       150   244    0        1      154      1      1.4   

     slope  ca  thal  target  
261      2   1     2       0  
94       1   0     2       1  
66       1   0     2       1  
29       0   0     2       1  
296      1   0     2       0  
230      2   0     2       0  
25       2   2     2       1  
111      2   1     3       1  
84       1   0     2       1  
258      1   0     2       0

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [6]:
lor = LogisticRegression()
dtc = DecisionTreeClassifier()

In [7]:
lor.fit(X_train,y_train)
dtc.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [10]:
y_pred_lor = lor.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy of Logistic Regression: ", accuracy_score(y_test,y_pred_lor))
print("Accuracy of Logistic Regression: ", accuracy_score(y_test,y_pred_dtc))

Accuracy of Logistic Regression:  0.9016393442622951
Accuracy of Logistic Regression:  0.8524590163934426


In [13]:
print("Logistic Regression Confusion Matrix")
pd.DataFrame(confusion_matrix(y_test,y_pred_lor), columns=list(range(0,2)))

Logistic Regression Confusion Matrix


0   1
0  26   6
1   0  29

In [14]:
print("Decision Tree Confusion Matrix")
pd.DataFrame(confusion_matrix(y_test,y_pred_dtc), columns=list(range(0,2)))

Decision Tree Confusion Matrix


0   1
0  24   8
1   1  28

In [15]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred_lor
result['Decision Tree Prediction'] = y_pred_dtc
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
209             0                               0                         0
269             0                               0                         0
161             1                               1                         1
99              1                               1                         1
134             1                               1                         1
66              1                               1                         1
159             1                               1                         1
176             0                               0                         0
178             0                               0                         0
240             0                               0                         0

In [16]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [20]:
print("For Logistic Regression Model")
print("-"*50)

cmf = pd.DataFrame(confusion_matrix(y_test,y_pred_lor), columns=list(range(0,2)))
print(cmf)

print("-"*50)
print("Precision : ", precision_score(y_test, y_pred_lor))
print("Recall : ", recall_score(y_test, y_pred_lor))
print("F1 Score : ", f1_score(y_test, y_pred_lor))

For Logistic Regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision :  0.8285714285714286
Recall :  1.0
F1 Score :  0.90625


In [22]:
print("Decision Tree Model")

print("-"*50)
cmf = pd.DataFrame(confusion_matrix(y_test,y_pred_dtc),columns=list(range(0,2)))
print(cmf)
print("-"*50)

print("Precision : ", precision_score(y_test,y_pred_dtc))
print("Recall : ", recall_score(y_test, y_pred_dtc))
print("F1 Score : ", f1_score(y_test, y_pred_dtc))


Decision Tree Model
--------------------------------------------------
    0   1
0  24   8
1   1  28
--------------------------------------------------
Precision :  0.7777777777777778
Recall :  0.9655172413793104
F1 Score :  0.8615384615384616


In [23]:
precision_score(y_test, y_pred_lor, average=None)


array([1.        , 0.82857143])

In [24]:
precision_score(y_test, y_pred_dtc, average=None)

array([0.96      , 0.77777778])

In [25]:
recall_score(y_test, y_pred_dtc,average=None)

array([0.75      , 0.96551724])